### ISSUE TITLE
MDN Issues

### ISSUE THREAD

**Issue by janeobenidi** [gabrielcarloto/flow-search-mdn#2]
[2022-11-20.txt](https://github.com/gabrielcarloto/flow-search-mdn/files/10048950/2022-11-20.txt)

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 11/20/2022 13:42:23
Exception:
Search MDN Exception: 
Websites: https://github.com/gabrielcarloto/flow-search-mdn
Author: Gabriel Carloto
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Search MDN|'node' is not recognized as an internal or external command,
operable program or batch file.

 ---> System.IO.InvalidDataException: Search MDN|'node' is not recognized as an internal or external command,
operable program or batch file.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 288
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 302
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from
[2022-11-20.txt](https://github.com/gabrielcarloto/flow-search-mdn/files/10048948/2022-11-20.txt)
[2022-11-20.txt](https://github.com/gabrielcarloto/flow-search-mdn/files/10048949/2022-11-20.txt)
 previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 626
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by gabrielcarloto** [comment]
It seems that node.js is not installed in your machine. Could you open a terminal and type `node -v` to check if it is installed? If it is not installed, please install from one of the sources in the [Installation](https://github.com/gabrielcarloto/flow-search-mdn#install-nodejs) section in README.

**Comment by janeobenidi** [comment]
> 

Oh I forgot to install it since I just formatted my pc. It works now. Thank you for the response!

**Comment by gabrielcarloto** [comment]
No problem. I think I will try to add some warning when node is not installed when I have time.
