### ISSUE TITLE
Plugin loading error

### ISSUE THREAD

**Issue by mishatoshi** [gabrielcarloto/flow-search-mdn#4]
Plugin loading error.
Log file:
PluginManager.InitializePluginsAsync - Fail to Init plugin: Search MDN
EXCEPTION OCCURS: System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
at void System.Text.Json.ThrowHelper.ThrowJsonReaderException(ref Utf8JsonReader json, ExceptionResource resource, byte nextByte, ReadOnlySpan bytes)
at bool System.Text.Json.Utf8JsonReader.Read()
at T System.Text.Json.Serialization.JsonConverter.ReadCore(ref Utf8JsonReader reader, JsonSerializerOptions options, ref ReadStack state)
--- End of inner exception stack trace ---
at void System.Text.Json.ThrowHelper.ReThrowWithPath(ref ReadStack state, JsonReaderException ex)
at T System.Text.Json.Serialization.JsonConverter.ReadCore(ref Utf8JsonReader reader, JsonSerializerOptions options, ref ReadStack state)
at TValue System.Text.Json.JsonSerializer.ReadCore(JsonConverter jsonConverter, ref Utf8JsonReader reader, JsonSerializerOptions options, ref ReadStack state) x 2
at TValue System.Text.Json.JsonSerializer.ContinueDeserialize(ref ReadBufferState bufferState, ref JsonReaderState jsonReaderState, ref ReadStack readStack, JsonConverter converter, JsonSerializerOptions options)
at async ValueTask System.Text.Json.JsonSerializer.ReadAllAsync(Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
at async Task Flow.Launcher.Core.Plugin.JsonRPCPlugin.InitSettingAsync() x 2 in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs:line 319
at async Task Flow.Launcher.Core.Plugin.JsonRPCPlugin.InitAsync(PluginInitContext context) in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/JsonRPCPlugin.cs:line 341
at async Task Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(string message, Func action) in C:/projects/flow-launcher/Flow.Launcher.Infrastructure/Stopwatch.cs:line 34
at async Task Flow.Launcher.Core.Plugin.PluginManager.InitializePluginsAsync(IPublicAPI api)+(?) => { } in C:/projects/flow-launcher/Flow.Launcher.Core/Plugin/PluginManager.cs:line 122

**Comment by gabrielcarloto** [comment]
Hey, I saw your other issue, but didn't answer it as you closed it as completed. Thought the error was gone.

This log doesn't tell me much because this error is not generated from Nodejs. Seems to be either my plugin not sending any data or some error in Flow Launcher, but I'm not sure.

The plugin works fine on my computer. Have you tried my [other plugin](https://github.com/gabrielcarloto/flow-search-npm)? If yes, can you use it normally? Have you tried reinstalling it? And when exactly this error shows up? Is it the instant after you enable it, or when you try to run in by typing the action keyword (`mdn` by default)?

**Comment by mishatoshi** [comment]
Your plugins (mdn and npm) stopped working in the latest version of Flow Launcher 1.11.0
Your other plugin (npm) throws a 522 error after waiting for a request.
The mdn plugin is disabled after launching the flow launcher.
When enabled in the settings, when you enter mdn 'request' gives an error.

I have installed:
Windows 10
Node.js LTS v18.12.1 (Fixed path to node.js in Flow Launcher settings)
Flow Launcher 1.11.0

After rearranging the plugin, 'npm' throws an error:
Please open new issue in: https://github.com/gabrielcarloto/flow-search-npm/issues/new
1. upload log file: C:\Users\Mikhail\AppData\Roaming\FlowLauncher\Logs\1.11.0\2023-01-16.txt
2. copy below exception message

Flow Launcher version: 1.11.0
OS Version: Microsoft Windows NT 10.0.19045.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\Mikhail\AppData\Local\Programs\Python\Python310\pythonw.exe
Node Path: C:\Users\Mikhail\AppData\Local\Volta\tools\image\node\18.12.1\node.exe
Date: 01/16/2023 22:20:01
Exception:
Search npm Exception: 
Websites: https://github.com/gabrielcarloto/flow-search-npm
Author: Gabriel Carloto
Version: 1.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: "node" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

 ---> System.IO.InvalidDataException: "node" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 287
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 292
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 307
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 811
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 785
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by gabrielcarloto** [comment]
Just tested in node v16.17.1 and v18.13.0, MDN is working fine, but NPM results in error 522, which is an error in the api server, not in the plugin (you can see this opening the [api url](https://api.npms.io/)).

![Cloudflare connection timed out](https://user-images.githubusercontent.com/68694907/212902960-ee992f50-1732-4386-9792-79cee6b23dec.png)

But mine doesn't throw an error, it just displays the error:

![Http error](https://user-images.githubusercontent.com/68694907/212903254-7d75b2e7-a9e8-443a-a0e3-dd8c1d2a208f.png)

I have one question, though. Do these characters also look like this to you?

![image](https://user-images.githubusercontent.com/68694907/212903938-608f180b-fdb4-4eda-933c-353b67e7a2ac.png)

**Comment by mishatoshi** [comment]
Thanks for the answer. Agree with the API error in the "npm" plugin.
But the "mdn" plugin does not want to work, after installation, Flow Launcher disables it, and when enabled in the Flow Launcher settings, the request after the 'mdn' keyword gives an error.
Also, in the Flow Launcher settings of the 'mdn' plugin, the choice of language for MDN search has disappeared.
I can't figure out what's wrong? If it works for you, but it gives me an error.

**Comment by gabrielcarloto** [comment]
This is really weird. The MDN plugin is essentially the same as the NPM. The only thing that changes is the api and the settings.

In the last screenshot I sent there are some characters I can't read. I assume it shows correctly to you. If yes, could you tell me what it says? Maybe there is some hint there.

**Comment by mishatoshi** [comment]
I reinstalled Flow Launcher, did a clean install (deleting all Flow.Launcher folders).
Problem solved with 'mdn' plugin, but 'npm' plugin doesn't work due to API (same as in your screenshot).
Thanks for your attention, I'm closing the issue.
